### ISSUE TITLE
Does the download plugin support xlsx files?

### ISSUE THREAD

**Issue by Louise-Huang** [jspreadsheet/plugins#8]
Hi,
I see that the official website only has examples of csv and xls, is there any support for xlsx? Another question is the exported excel file cannot display the column title and nested title of jspreadsheet. Is there any way to add the column title and nested title in the first few rows of the data?

**Comment by max533** [comment]
Yeah, I have run into the same issue. 
Does any update now about this issue?

**Comment by me21** [comment]
The plugin is now called "xls", by the way.
Does it support the free version - https://github.com/jspreadsheet/ce?

**Comment by Ruan-Miguel** [comment]
XLS is a deprected plugin. It raises an error when the user tries to use it, but yes you can use in the CE.

There is support for XLSX that runs in the frontend. That is an extension and is only available in the PRO distributions.

https://jspreadsheet.com/products/import-from-xlsx
